# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
    - RGL_USE_NULL=TRUE

addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial multiverse"
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe"
    packages:
    - libglu1-mesa-dev # legacy GL RenderSystem only

after_success:
    - Rscript -e 'covr::codecov()'
